/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ShellRouteImport } from './routes/shell'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-users': typeof AdminUsersRoute
  '/audit-log': typeof AuditLogRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/maps': typeof MapsRoute
  '/packages': typeof PackagesRoute
  '/plugins': typeof PluginsRoute
  '/shell': typeof ShellRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-users': typeof AdminUsersRoute
  '/audit-log': typeof AuditLogRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/maps': typeof MapsRoute
  '/packages': typeof PackagesRoute
  '/plugins': typeof PluginsRoute
  '/shell': typeof ShellRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-users': typeof AdminUsersRoute
  '/audit-log': typeof AuditLogRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/maps': typeof MapsRoute
  '/packages': typeof PackagesRoute
  '/plugins': typeof PluginsRoute
  '/shell': typeof ShellRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-users'
    | '/audit-log'
    | '/login'
    | '/logs'
    | '/maps'
    | '/packages'
    | '/plugins'
    | '/shell'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-users'
    | '/audit-log'
    | '/login'
    | '/logs'
    | '/maps'
    | '/packages'
    | '/plugins'
    | '/shell'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/admin-users'
    | '/audit-log'
    | '/login'
    | '/logs'
    | '/maps'
    | '/packages'
    | '/plugins'
    | '/shell'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuditLogRoute: typeof AuditLogRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MapsRoute: typeof MapsRoute
  PackagesRoute: typeof PackagesRoute
  PluginsRoute: typeof PluginsRoute
  ShellRoute: typeof ShellRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shell': {
      id: '/shell'
      path: '/shell'
      fullPath: '/shell'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuditLogRoute: AuditLogRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MapsRoute: MapsRoute,
  PackagesRoute: PackagesRoute,
  PluginsRoute: PluginsRoute,
  ShellRoute: ShellRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
