name: python-tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
        working-directory: admin
      - name: Run pytest
        run: pytest
        working-directory: admin
